// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadGeneratedFile(arg1) {
  return window['go']['main']['App']['DownloadGeneratedFile'](arg1);
}

export function GenerateGRPC(arg1, arg2) {
  return window['go']['main']['App']['GenerateGRPC'](arg1, arg2);
}

export function GetCurrentUser(arg1) {
  return window['go']['main']['App']['GetCurrentUser'](arg1);
}

export function GetGeneratedFiles() {
  return window['go']['main']['App']['GetGeneratedFiles']();
}

export function GetPBFiles() {
  return window['go']['main']['App']['GetPBFiles']();
}

export function LoginUser(arg1, arg2) {
  return window['go']['main']['App']['LoginUser'](arg1, arg2);
}

export function LogoutUser(arg1) {
  return window['go']['main']['App']['LogoutUser'](arg1);
}

export function ReadGeneratedFile(arg1) {
  return window['go']['main']['App']['ReadGeneratedFile'](arg1);
}

export function ReadPB(arg1) {
  return window['go']['main']['App']['ReadPB'](arg1);
}

export function RegisterUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegisterUser'](arg1, arg2, arg3);
}

export function SavePB(arg1, arg2) {
  return window['go']['main']['App']['SavePB'](arg1, arg2);
}
