// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadGeneratedFile(arg1:string):Promise<string>;

export function GenerateGRPC(arg1:string,arg2:string):Promise<string>;

export function GetCurrentUser(arg1:string):Promise<string>;

export function GetGeneratedFiles():Promise<Array<Record<string, any>>>;

export function GetPBFiles():Promise<Array<Record<string, any>>>;

export function LoginUser(arg1:string,arg2:string):Promise<string>;

export function LogoutUser(arg1:string):Promise<string>;

export function ReadGeneratedFile(arg1:string):Promise<string>;

export function ReadPB(arg1:string):Promise<string>;

export function RegisterUser(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SavePB(arg1:string,arg2:string):Promise<string>;
